apiVersion: v1
kind: ConfigMap
metadata:
  name: bot-config
data:
  telegram_bot_id: "<Telegram Bot token>"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: math-bot
  labels:
    app: math
spec:
  replicas: 1
  selector:
    matchLabels:
      app: math
  template:
    metadata:
      labels:
        app: math
    spec:
      containers:
      - name: math
        image: mastrogiovanni/math
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: TELEGRAM_BOT_ID
            valueFrom:
              configMapKeyRef:
                name: bot-config
                key: telegram_bot_id
